apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  namespace: ckad
  labels:
    name: security-context-demo
spec:
  containers:
  - name: security-context-demo
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
