apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: ckad
  labels:
    tier: backend
    team: artemidis
spec:
  containers:
  - name: pod-2
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
