apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: server-deployment-hpa
  namespace: ckad
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-deployment
  minReplicas: 4
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
