apiVersion: v1
kind: Pod
metadata:
  name: consuming-pod
  namespace: ckad
  labels:
    name: consuming-pod
spec:
  volumes:
    - name: pv-shared
      persistentVolumeClaim:
        claimName: logs-pvc
  containers:
  - name: consuming-pod
    image: nginx
    volumeMounts:
      - mountPath: /var/log/nginx
        name: pv-shared
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
