apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
  namespace: ckad
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: /var/logs