apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  namespace: ckad
  labels:
    name: storage-pod
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  containers:
  - name: storage-pod-1
    image: alpine:3.12.0
    command: ['sh', '-c-', 'while true; do sleep 60; done;']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /etc/a
        name: shared-volume
  - name: storage-pod-2
    image: alpine:3.12.0
    command: ['sh', '-c-', 'while true; do sleep 60; done;']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /etc/b
        name: shared-volume