apiVersion: v1
kind: Pod
metadata:
  name: custom-cmd
  namespace: ckad
  labels:
    name: custom-cmd
spec:
  containers:
  - name: custom-cmd
    image: busybox
    command: ["sh", "-c", "top-analyzer --all"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
