apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: ckad
  labels:
    run: web-server
spec:
  containers:
  - name: web-server
    image: nginx
    startupProbe:
      httpGet:
        path: /
        port: web-server-port
    readinessProbe:
      httpGet:
        path: /
        port: web-server-port
      initialDelaySeconds: 5
    livenessProbe:
      httpGet:
        path: /
        port: web-server-port
      initialDelaySeconds: 10
      periodSeconds: 30
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
      - name: web-server-port
        containerPort: 80
